#!/bin/sh
# temporarily shut down an interface and randomize the mac,
# requires the macchanger tool.
#
# place in /etc/network/if-post-down.d to renew the mac everytime
# a network interface is brought down (recent versions of
# NetworkManager no longer support if-pre-up.d)
#
# felix@tribut.de

LOGFILE="`mktemp`"
IFSTATE="`ip addr show dev \"$IFACE\" 2>>\"$LOGFILE\"`"

if [ -n "$IFSTATE" ]; then
	FAILED="0"
	PRESTATE="`ip addr show dev \"$IFACE\" up 2>>\"$LOGFILE\"`"

	[ -n "$PRESTATE" ] && ip link set dev "$IFACE" down >>"$LOGFILE" 2>&1
	macchanger -A "$IFACE" >>"$LOGFILE" 2>&1 || FAILED=1
	[ -n "$PRESTATE" ] && ip link set dev "$IFACE" up >>"$LOGFILE" 2>&1

	if [ "$FAILED" = "1" ]; then
		echo "ERROR while trying to randomize MAC for $IFACE" | cat - "$LOGFILE" | logger -t randomize-mac -p user.err
	else
		echo "MAC successfully randomized for $IFACE" | logger -t randomize-mac -p user.notice
	fi
else
	echo "Interface $IFACE does not exist, skipping..." | logger -t randomize-mac -p user.info
fi

rm -f "$LOGFILE"
